# Generated by Django 3.0.4 on 2020-03-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200317_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='breed',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='age',
        ),
    ]
