# Generated by Django 3.0.4 on 2020-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200317_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoothie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('drink_type', models.CharField(choices=[('G', 'Greens'), ('D', 'Detox'), ('S', 'Sweet')], default='G', max_length=1)),
            ],
        ),
    ]
