# Generated by Django 3.0.4 on 2020-03-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_smoothie'),
    ]

    operations = [
        migrations.AddField(
            model_name='smoothie',
            name='fruit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Fruit'),
        ),
    ]
