# Generated by Django 3.0.4 on 2020-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_smoothie_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('health_benefits', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fruit',
            name='vitamins',
            field=models.ManyToManyField(to='main_app.Vitamin'),
        ),
    ]
