# Generated by Django 3.0.4 on 2020-03-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200320_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='region',
        ),
    ]
