# Generated by Django 3.0.4 on 2020-03-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200323_1859'),
        ('main_app', '0012_auto_20200323_2245'),
    ]

    operations = [
    ]
