# Generated by Django 3.0.4 on 2020-03-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_juice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Juice'),
        ),
    ]
